### ISSUE TITLE
Incorrect processed data splits

### ISSUE THREAD

**Issue by adrianeboyd** [budh333/UnSilence_VOC#6]
Hi, I was looking at using this data for a demo and I noticed that the published processed data splits don't correspond to the description in the paper. It looks like all the data has ended up in the train split because the internal paths that are used to specify train/dev/test refer to an older path and they are also in a windows-specific format.

I originally download the data from https://zenodo.org/record/7129316 and it looks like the same version is in this repo, too?

This probably isn't the solution you want in the end, but a minimal patch to the notebook to demonstrate the issue, along with the updated data:

https://github.com/budh333/UnSilence_VOC/compare/main...adrianeboyd:UnSilence_VOC:bugfix/processed-data-splits?expand=1

**Comment by ktodorov** [comment]
Hi @adrianeboyd and thank you for finding this. You were correct about the splits being corrupted and that it was because the paths were incorrect. However, this was not due to OS-specific paths but instead due to some changes on our side that made the pre-saved splits incorrect. 

The splits have now been restored to their original state, as mentioned in the paper and I have also updated the data around the cached definitions of these, including the process_data notebook which is actually used to generate the splits. 

I believe the latest changes should solve your issues so I will mark this as closed for now. If you have any other doubts or problems, feel free to create another Issue here and we will do our best to help. And thank you once again for reporting this!

**Comment by adrianeboyd** [comment]
Thanks for updating the processed data in the repo! This is sufficient for the demo I was working on.

I can understand that there's no particular need on your end to spend effort to make this more compatible, but a comment in the notebook that it only works in windows might be helpful for future users? It's hard to see what's going on in the `.pickle` data and it took me a bit to figure out what was going on.

If you run `process_data.ipynb` on a platform other than windows, the data is all selected as train data because the paths do not have the exact same string representation underneath:

A `path_by_split.pickle` path:

```
'..\\data\\annotated_data\\A\\NL-HaNA_1.04.02_6848_0031.txt'
```

vs. a linux path:

```
'../data/annotated_data/A/NL-HaNA_1.04.02_6848_0031.txt'
```
